<%@ Page Title="" Language="C#" MasterPageFile="~/U n G MasterPage.master" AutoEventWireup="true" CodeFile="about_us.aspx.cs" Inherits="Default2" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <html>
    <head>

        <style>
            .p1:hover{
           color:red;
             font-size: large;
            }
        </style>
	<title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, Slider Image jQuery, jQuery Image Slider" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" media="screen" />
	<style type="text/css">a#vlb{display:none}</style>
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
        <body>
    <div style="width:100%;">
        <table >
            <tr>
                <td style="width:30%;height:100%;"></td>
                <td>
                    <!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images">
<a href="#"><img src="data1/images/7.jpg" alt="7" title="7" id="wows0"/></a>
<a href="#"><img src="data1/images/9.jpg" alt="9" title="9" id="wows1"/></a>
<a href="#"><img src="data1/images/maxresdefault_1.jpg" alt="maxresdefault (1)" title="maxresdefault (1)" id="wows2"/></a>
<a href="#"><img src="data1/images/maxresdefault_2.jpg" alt="maxresdefault (2)" title="maxresdefault (2)" id="wows3"/></a>
<a href="#"><img src="data1/images/jolly_llb_2_first_look.jpg" alt="Jolly_LLB_2_first_look" title="Jolly_LLB_2_first_look" id="wows4"/></a>
<a href="#"><img src="data1/images/31fir173_647_053115105554.jpg" alt="31fir17-3_647_053115105554" title="31fir17-3_647_053115105554" id="wows5"/></a>
</div>
<div class="ws_bullets"><div>
<a href="#wows0" title="7">1</a>
<a href="#wows1" title="9">2</a>
<a href="#wows2" title="maxresdefault (1)">3</a>
<a href="#wows3" title="maxresdefault (2)">4</a>
<a href="#wows4" title="Jolly_LLB_2_first_look">5</a>
<a href="#wows5" title="31fir17-3_647_053115105554">6</a>
</div></div>
<a style="display:none" href="http://wowslider.com">Image Slider by WOWSlider.com v1.7</a>
	<a href="#" class="ws_frame"></a>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
                    </td>
                 <td style="width:30%;height:100%;"></td>
            </tr>

            <tr>
                <td style="width:30%;height:100%;"></td>
                 <td style="box-shadow: 10px 10px 5px #808080;">
                      <p class="p1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ebooking.com is a one-stop portal for Your tickets Your way to Movies, Concerts, Plays and Sporting Events. The website offers the audience a facility of buying tickets online along with host of offers & features that would keep them entertained.
                           We encourage you to visit the site and have fun while you explore. 
            Buy all your tickets and satisfy your appetite for entertainment only with Ticketplease!!!</p>
                      <p class="p1"><br />&nbsp;&nbsp;&nbsp;&nbsp;
            Ebooking.com has tied up with leading multiplexes along with several single screen theatres across India to provide customers the convenience of ticketing almost anywhere. 
                    The website not only caters to film fans but also intends to mobilize the passion of music and sports fans to buy tickets to concert and events across India.
                </p>
                 </td>
                 <td style="width:30%;height:100%;"></td>
            </tr>
        </table><br />
        <br />
         <div style="text-align:center; vertical-align:middle;color:firebrick;font-family:serif"><h3>..Latest Movies Trailors and Songs Videos..</h3></div>
        <div>
      <table width="100%" style="height:250px">     
  <tr><td><video src="videos/1.mp4"  width="320" height="240" controls/></td>
 
      <td><video src="videos/2.mp4"  width="320" height="240" controls/></td>
           <td><video src="videos/3.mp4"  width="320" height="240" controls /></td> 
        <td><video src="videos/4.mp4"  width="320" height="240" controls /></td>
      
  </tr> 
           <tr>
             <td style="color:orange">
                 Album Song<br />
             </td>
              <td style="color:orange">
                  Trailer Song<br />
             </td>
             <td style="color:orange">
                  Punjabi Song<br />
             </td>
             <td style="color:orange">
                  Trailer Song<br />
             </td>
         </tr>
      </table>
  </div>

    </div>
            </body>
        </html>
</asp:Content>

