
<%@ Page Title="" Language="C#" MasterPageFile="~/U n G MasterPage.master" AutoEventWireup="true" CodeFile="Home.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <html>
    <head>
	<title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, Slider Image jQuery, jQuery Image Slider" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" media="screen" />
	<style type="text/css">
     
     a#vlb{display:none}
	    
	</style>
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
   </head>
    <body>

    <div style="width:100%; background:url(images/11.png)">
   <table style="width:100%;">
       <tr>
       <td style="width:10%;"></td>
           
           <td>              
 <div style="text-align:center; vertical-align:middle;color:firebrick;font-family:serif;">
      <center><div>
        <div>
            <asp:Label ID="lblmsg" runat="server" Text=""></asp:Label><br />
        <h4><asp:Label ID="lblc" runat="server" Text="Country"></asp:Label> &nbsp;<asp:DropDownList ID="ddlcountry" runat="server" Height="20px" Width="96px" >
            <asp:ListItem>India</asp:ListItem>
            </asp:DropDownList>
            </h4> 
        </div>

        <div>
          <h4><asp:Label ID="lblstate" runat="server" Text="Select State"></asp:Label> &nbsp;<asp:DropDownList ID="ddlstate" runat="server" Height="16px" Width="104px"><asp:ListItem>Andhra pradesh</asp:ListItem>
                 <asp:ListItem>Bihar</asp:ListItem>
                 <asp:ListItem>Chattisgarh</asp:ListItem>
                 <asp:ListItem>Goa</asp:ListItem>
                 <asp:ListItem>Himanchal Pradesh </asp:ListItem>
                 <asp:ListItem>Jharkhand</asp:ListItem>
                 <asp:ListItem>Karnatka</asp:ListItem>
                 <asp:ListItem>Madhya Pradesh </asp:ListItem>
                 <asp:ListItem>Nagpur</asp:ListItem>
                 <asp:ListItem>Orrisa</asp:ListItem>
                 <asp:ListItem>tripura</asp:ListItem>
                 <asp:ListItem>Sikkim</asp:ListItem>
                 <asp:ListItem>Orrisa</asp:ListItem>
                <asp:ListItem>Uttar Pradesh</asp:ListItem>
                 <asp:ListItem>West bengal</asp:ListItem>
                 </asp:DropDownList>
             </h4>
        </div>

        <div>
             <h4><asp:Label ID="lblcity" runat="server" Text="Select City"></asp:Label>&nbsp;<asp:DropDownList ID="ddlcity" runat="server" >
                 <asp:ListItem>Ahemdabad</asp:ListItem>
                 <asp:ListItem>Barabanki</asp:ListItem>
                 <asp:ListItem>Dehradun</asp:ListItem>
                 <asp:ListItem>faridabad</asp:ListItem>
                 <asp:ListItem>Hasinapur</asp:ListItem>
                 <asp:ListItem>Gorakhpur</asp:ListItem>
                 <asp:ListItem>Imphal</asp:ListItem>
                 <asp:ListItem>Jaipur</asp:ListItem>
                 <asp:ListItem>Kolkata</asp:ListItem>
                 <asp:ListItem>Lucknow</asp:ListItem>
                 <asp:ListItem></asp:ListItem>
                 <asp:ListItem>Mumbai</asp:ListItem>
                 <asp:ListItem>Noida</asp:ListItem>
                 <asp:ListItem>Pune</asp:ListItem>
                 <asp:ListItem>Ooty</asp:ListItem>
                 <asp:ListItem>Raibarely</asp:ListItem>
                 <asp:ListItem>Surat</asp:ListItem>
                 <asp:ListItem>trivanantpuram</asp:ListItem>
                 <asp:ListItem>Varanasi</asp:ListItem>
                 </asp:DropDownList>
             </h4>
            <br /><br />
    <asp:Button ID="proceedbtn" runat="server" Text="Proceed"  BackColor="mediumseagreen" color="white" 
          BorderColor="MediumSeaGreen" Font-Bold="True" OnClick="proceedbtn_Click" />

        </div>
        <br />
        <br />
    </div>
</center>

     <h3 style="color:mediumseagreen;font:bold;">Choose your Favouraite:</h3><br />
     <asp:RadioButton ID="rbmovie" runat="server" value="Movies" OnCheckedChanged="rbmovive_CheckedChanged" AutoPostBack="True" GroupName="rb1" />Movies
     <asp:RadioButton ID="rbevent" runat="server"  value="Events" OnCheckedChanged="rbevent_CheckedChanged" AutoPostBack="True" GroupName="rb1"/>Events
     <asp:RadioButton ID="rbsports" runat="server" value="Sports" OnCheckedChanged="rbsports_CheckedChanged" AutoPostBack="True"  GroupName="rb1"/>Sports<br /><br />
  
     
 </div>            
 </td>
           <td style="width:10%;"></td>
    <td style="width:50%;">
        
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images">
<a href="#"><img src="data1/images/7.jpg" alt="7" title="7" id="wows0"/></a>
<a href="#"><img src="data1/images/9.jpg" alt="9" title="9" id="wows1"/></a>
<a href="#"><img src="data1/images/maxresdefault_1.jpg" alt="maxresdefault (1)" title="maxresdefault (1)" id="wows2"/></a>
<a href="#"><img src="data1/images/maxresdefault_2.jpg" alt="maxresdefault (2)" title="maxresdefault (2)" id="wows3"/></a>
<a href="#"><img src="data1/images/jolly_llb_2_first_look.jpg" alt="Jolly_LLB_2_first_look" title="Jolly_LLB_2_first_look" id="wows4"/></a>
<a href="#"><img src="data1/images/31fir173_647_053115105554.jpg" alt="31fir17-3_647_053115105554" title="31fir17-3_647_053115105554" id="wows5"/></a>
</div>
<div class="ws_bullets"><div>
<a href="#wows0" title="7">1</a>
<a href="#wows1" title="9">2</a>
<a href="#wows2" title="maxresdefault (1)">3</a>
<a href="#wows3" title="maxresdefault (2)">4</a>
<a href="#wows4" title="Jolly_LLB_2_first_look">5</a>
<a href="#wows5" title="31fir17-3_647_053115105554">6</a>
</div></div>
<a style="display:none" href="http://wowslider.com">Image Slider by WOWSlider.com v1.7</a>
	<a href="#" class="ws_frame"></a>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
      
        <div style="height:100px;">
        <marquee  behavior="round">
            <img src="images/2014_winter_paralympics_sochi_2014_olympics_93037_602x339.jpg" height="100px" />
            <img src="images/Jolly_LLB_2_first_look.jpg" height="100px"/>
            <img src="images/maxresdefault%20(2).jpg" height="100px" />
            <img src="images/maxresdefault.jpg" height="100px"/>
            <img src="images/maxresdefault%20(1).jpg" height="100px"/>
            <img src="images/31fir17-3_647_053115105554.jpg" height="100px"/>
            <img src="images/sochi_2014_people_clothing_symbols_olympics_93343_602x339.jpg" height="100px"/>
            <img src="images/prometheus_alien_space_jockey_alien_99648_300x188.jpg" height="100px"/>
            <img src="images/23-1480859108-134013-khaskhabar.jpg" height="100px" />
            <img src="images/2014_winter_paralympics_sochi_2014_olympics_93037_602x339.jpg" height="100px" />
            <img src="images/Jolly_LLB_2_first_look.jpg" height="100px"/>
            <img src="images/maxresdefault%20(2).jpg" height="100px" />
            <img src="images/maxresdefault.jpg" height="100px"/>
            <img src="images/maxresdefault%20(1).jpg" height="100px"/>
            <img src="images/31fir17-3_647_053115105554.jpg" height="100px"/>
            <img src="images/sochi_2014_people_clothing_symbols_olympics_93343_602x339.jpg" height="100px"/>
            <img src="images/prometheus_alien_space_jockey_alien_99648_300x188.jpg" height="100px"/>
            <img src="images/23-1480859108-134013-khaskhabar.jpg" height="100px" />
            <img src="images/2014_winter_paralympics_sochi_2014_olympics_93037_602x339.jpg" height="100px" />
            <img src="images/Jolly_LLB_2_first_look.jpg" height="100px"/>
            <img src="images/maxresdefault%20(2).jpg" height="100px" />
            <img src="images/maxresdefault.jpg" height="100px"/>
            <img src="images/maxresdefault%20(1).jpg" height="100px"/>
            <img src="images/31fir17-3_647_053115105554.jpg" height="100px"/>
            <img src="images/sochi_2014_people_clothing_symbols_olympics_93343_602x339.jpg" height="100px"/>
            <img src="images/prometheus_alien_space_jockey_alien_99648_300x188.jpg" height="100px"/>
            <img src="images/23-1480859108-134013-khaskhabar.jpg" height="100px" />
        </marquee>
            </div>

 <!-- <img src="images/background-wallpapers-10.jpg" height="300px" width="300px"/>!-->

    </td>
    </tr>
           
   </table>
        

        <div style="text-align:center; vertical-align:middle;color:firebrick;font-family:serif"><h3>..Latest Movies Trailors and Songs Videos..</h3></div>
        <div class="v1">
     <!-- <marquee direction="left" onmouseover="this.stop();" onmouseout="this.start();"> !--> <table width="100%" style="height:250px">    
  <tr><td><video src="videos/1.mp4"  width="320" height="300" controls/></td>
              <td><video src="videos/3.mp4"  width="320" height="300" controls /></td> 
              <td><video src="videos/8.mp4"  width="320" height="300" controls /></td>
       <td><video src="videos/9.mp4"  width="320" height="300" controls /></td>
  </tr> 
         <tr>
             <td style="color:orange">
                 Album Song<br />
             </td>
              <td style="color:orange">
                  Trailer Song<br />
             </td>
             <td style="color:orange">
                  Punjabi Song<br />
             </td>
             <td style="color:orange">
                  Trailer Song<br />
             </td>
         </tr>
                </table>
  </div>
    </div>
        </body>
        </html>
</asp:Content>

